### ISSUE TITLE
error running make

### ISSUE THREAD

**Issue by veso266** [Opendigitalradio/toolame-dab#13]
Hi I've tried building toolame-dab and I've installed zeromq-4.0.3 (zeromq installs fine) but when I run make I get the following two errors at the end.

CMakeFiles/toolame.dir/zmqoutput.c.o: In function `zmqoutput_open':
zmqoutput.c:(.text+0x21): undefined reference to `zmq_ctx_new'
CMakeFiles/toolame.dir/zmqoutput.c.o: In function `zmqoutput_close':
zmqoutput.c:(.text+0x2df): undefined reference to `zmq_ctx_destroy'
collect2: error: ld returned 1 exit status
make[2]: *** [toolame-dab] Error 1
make[1]: *** [CMakeFiles/toolame.dir/all] Error 2
make: *** [all] Error 2

I don't know what to do now so Thanks fro Helping and Best Regards

**Comment by mpbraendli** [comment]
What system are you running on ?
Did you install zmq manually or through your distribution's package manager ?
What is the output of the following three commands ?

    pkg-config --cflags --libs libzmq
    pkg-config --cflags --libs libzmq3
    pkg-config --cflags --libs libzmq5

I am trying to understand if the package on your system might be called something else than libzmq.
mpb

**Comment by veso266** [comment]
Hi thanks for help I am on Ubuntu 14.04 and I first try to bild it from source and failed 

I then just install version 4.0.4 via sudo apt-get install libzmq3-dev

And it magicly worked. 



—

**Comment by mpbraendli** [comment]
Great !
